import type { SecurityDefinitionMetadata } from './security-definition';
import type { ValidationRuleDefinitionMetadata } from './validation-rule-definition';
import type { DependencyDefinition, PackageDefinition, VersionDefinition } from './version-package-definition';
import { verticalOwnership } from './core-fixtures';

export const serviceJobCardValidationRules: ValidationRuleDefinitionMetadata[] = [
  {
    validationRuleId: 'val_job_card_customer_required_submit',
    entityId: 'ent_service_job_card',
    apiName: 'job_card_customer_required_submit',
    label: 'Customer required before submit',
    ruleType: 'required_when',
    triggers: ['before_submit'],
    severity: 'blocking_error',
    expression: { op: 'is_not_empty', field: 'customer_id' },
    message: 'Customer is required before submitting a service job card.',
    ownership: verticalOwnership,
    lifecycle: { metadataStatus: 'active' },
    version: { versionId: 'ver_val_job_card_customer_required_1_0_0', version: '1.0.0', status: 'active' },
  },
];

export const serviceJobCardSecurityDefinitions: SecurityDefinitionMetadata[] = [
  {
    securityDefinitionId: 'sec_customer_workshop_access',
    entityId: 'ent_customer',
    apiName: 'customer_workshop_access',
    label: 'Customer Workshop Access',
    subjects: { roleCodes: ['service_advisor', 'service_manager'] },
    objectPermissions: [
      { operation: 'read', effect: 'allow' },
      { operation: 'create', effect: 'allow' },
      { operation: 'update', effect: 'allow' },
    ],
    fieldPermissions: [],
    actionPermissions: [],
    viewPermissions: [
      { viewId: 'view_customer_default_list', effect: 'allow' },
      { viewId: 'view_customer_default_form', effect: 'allow' },
      { viewId: 'view_customer_lookup', effect: 'allow' },
    ],
    apiPermissions: [{ apiScope: 'read', effect: 'allow' }, { apiScope: 'write', effect: 'allow' }],
    recordScope: { scopeType: 'tenant_records' },
    ownership: verticalOwnership,
    lifecycle: { metadataStatus: 'active' },
    version: { versionId: 'ver_sec_customer_workshop_1_0_0', version: '1.0.0', status: 'active' },
  },
  {
    securityDefinitionId: 'sec_vehicle_workshop_access',
    entityId: 'ent_vehicle',
    apiName: 'vehicle_workshop_access',
    label: 'Vehicle Workshop Access',
    subjects: { roleCodes: ['service_advisor', 'service_manager'] },
    objectPermissions: [
      { operation: 'read', effect: 'allow' },
      { operation: 'create', effect: 'allow' },
      { operation: 'update', effect: 'allow' },
    ],
    fieldPermissions: [],
    actionPermissions: [],
    viewPermissions: [
      { viewId: 'view_vehicle_default_list', effect: 'allow' },
      { viewId: 'view_vehicle_default_form', effect: 'allow' },
      { viewId: 'view_vehicle_lookup', effect: 'allow' },
    ],
    apiPermissions: [{ apiScope: 'read', effect: 'allow' }, { apiScope: 'write', effect: 'allow' }],
    recordScope: { scopeType: 'tenant_records' },
    ownership: verticalOwnership,
    lifecycle: { metadataStatus: 'active' },
    version: { versionId: 'ver_sec_vehicle_workshop_1_0_0', version: '1.0.0', status: 'active' },
  },
  {
    securityDefinitionId: 'sec_service_job_card_service_advisor',
    entityId: 'ent_service_job_card',
    apiName: 'service_job_card_service_advisor_access',
    label: 'Service Advisor Access',
    subjects: { roleCodes: ['service_advisor'] },
    objectPermissions: [
      { operation: 'read', effect: 'allow' },
      { operation: 'create', effect: 'allow' },
      { operation: 'update', effect: 'allow' },
      { operation: 'submit', effect: 'allow' },
      { operation: 'close', effect: 'deny' },
    ],
    fieldPermissions: [
      { fieldId: 'fld_manager_notes', access: 'hidden' },
    ],
    actionPermissions: [
      { actionId: 'submit', effect: 'allow' },
      { actionId: 'close', effect: 'deny', disabledReason: 'Only a service manager can close the job card.' },
    ],
    viewPermissions: [{ viewId: 'view_service_job_card_form', effect: 'allow' }],
    apiPermissions: [{ apiScope: 'read', effect: 'allow' }, { apiScope: 'write', effect: 'allow' }],
    recordScope: { scopeType: 'node_records' },
    ownership: verticalOwnership,
    lifecycle: { metadataStatus: 'active' },
    version: { versionId: 'ver_sec_service_advisor_1_0_0', version: '1.0.0', status: 'active' },
  },
  {
    securityDefinitionId: 'sec_service_job_card_service_manager',
    entityId: 'ent_service_job_card',
    apiName: 'service_job_card_service_manager_access',
    label: 'Service Manager Access',
    subjects: { roleCodes: ['service_manager'] },
    objectPermissions: [
      { operation: 'read', effect: 'allow' },
      { operation: 'create', effect: 'allow' },
      { operation: 'update', effect: 'allow' },
      { operation: 'submit', effect: 'allow' },
      { operation: 'close', effect: 'allow' },
    ],
    fieldPermissions: [
      { fieldId: 'fld_manager_notes', access: 'edit' },
    ],
    actionPermissions: [
      { actionId: 'submit', effect: 'allow' },
      { actionId: 'close', effect: 'allow' },
    ],
    viewPermissions: [{ viewId: 'view_service_job_card_form', effect: 'allow' }],
    apiPermissions: [{ apiScope: 'read', effect: 'allow' }, { apiScope: 'write', effect: 'allow' }],
    recordScope: { scopeType: 'node_records' },
    ownership: verticalOwnership,
    lifecycle: { metadataStatus: 'active' },
    version: { versionId: 'ver_sec_service_manager_1_0_0', version: '1.0.0', status: 'active' },
  },
];

export const serviceJobCardVersions: VersionDefinition[] = [
  {
    versionId: 'ver_customer_1_0_0',
    metadataObjectId: 'ent_customer',
    metadataObjectType: 'EntityDefinition',
    version: '1.0.0',
    status: 'published',
    changeType: 'non_breaking',
    immutable: true,
    metadataHash: 'sha256-customer-1',
    publishedAt: '2026-05-11T00:00:00.000Z',
  },
  {
    versionId: 'ver_vehicle_1_0_0',
    metadataObjectId: 'ent_vehicle',
    metadataObjectType: 'EntityDefinition',
    version: '1.0.0',
    status: 'published',
    changeType: 'non_breaking',
    immutable: true,
    metadataHash: 'sha256-vehicle-1',
    publishedAt: '2026-05-11T00:00:00.000Z',
  },
  {
    versionId: 'ver_service_job_card_1_0_0',
    metadataObjectId: 'ent_service_job_card',
    metadataObjectType: 'EntityDefinition',
    version: '1.0.0',
    status: 'published',
    changeType: 'non_breaking',
    immutable: true,
    metadataHash: 'sha256-service-job-card-1',
    publishedAt: '2026-05-11T00:00:00.000Z',
  },
];

export const serviceJobCardDependencies: DependencyDefinition[] = [
  {
    dependencyId: 'dep_job_card_customer_field_to_rel',
    sourceObjectId: 'fld_customer_id',
    targetObjectId: 'rel_job_card_customer',
    dependencyType: 'relationship_reference',
    impactSeverity: 'safe',
    required: true,
    migrationRequired: false,
  },
];

export const serviceJobCardPackage: PackageDefinition = {
  packageId: 'pkg_automotive_service',
  apiName: 'automotive_service',
  label: 'Automotive Service',
  packageType: 'vertical',
  ownership: verticalOwnership,
  contents: [
    { objectId: 'ent_customer', objectType: 'EntityDefinition', versionId: 'ver_customer_1_0_0' },
    { objectId: 'ent_vehicle', objectType: 'EntityDefinition', versionId: 'ver_vehicle_1_0_0' },
    { objectId: 'ent_service_job_card', objectType: 'EntityDefinition', versionId: 'ver_service_job_card_1_0_0' },
    { objectId: 'fld_customer_full_name', objectType: 'FieldDefinition' },
    { objectId: 'fld_customer_mobile', objectType: 'FieldDefinition' },
    { objectId: 'fld_vehicle_registration_number', objectType: 'FieldDefinition' },
    { objectId: 'fld_vehicle_vin', objectType: 'FieldDefinition' },
    { objectId: 'fld_job_card_number', objectType: 'FieldDefinition' },
    { objectId: 'fld_customer_id', objectType: 'FieldDefinition' },
    { objectId: 'fld_vehicle_id', objectType: 'FieldDefinition' },
    { objectId: 'fld_service_type', objectType: 'FieldDefinition' },
    { objectId: 'fld_job_status', objectType: 'FieldDefinition' },
    { objectId: 'fld_complaint_notes', objectType: 'FieldDefinition' },
    { objectId: 'fld_estimated_amount', objectType: 'FieldDefinition' },
    { objectId: 'fld_manager_notes', objectType: 'FieldDefinition' },
    { objectId: 'rel_job_card_customer', objectType: 'RelationshipDefinition' },
    { objectId: 'rel_job_card_vehicle', objectType: 'RelationshipDefinition' },
    { objectId: 'val_job_card_customer_required_submit', objectType: 'ValidationRuleDefinition' },
    { objectId: 'sec_customer_workshop_access', objectType: 'SecurityDefinition' },
    { objectId: 'sec_vehicle_workshop_access', objectType: 'SecurityDefinition' },
    { objectId: 'sec_service_job_card_service_advisor', objectType: 'SecurityDefinition' },
    { objectId: 'sec_service_job_card_service_manager', objectType: 'SecurityDefinition' },
  ],
  dependencies: serviceJobCardDependencies,
  status: 'active',
  version: '1.0.0',
  publishSafety: 'safe',
  rollbackSupported: true,
};
